Trying:
    lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul
Expecting nothing
ok
Trying:
    lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
Expecting:
    array([[ 7, 10],
           [15, 22]])
ok
Trying:
    lazy_matrix_mul([[1, 2]], [[3, 4], [5, 6]])
Expecting:
    array([[13, 16]])
ok
Trying:
    list1 = [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
Expecting nothing
ok
Trying:
    list2 = [[1, -1, 2], [2, -1, 2], [3, -3, 0]]
Expecting nothing
ok
Trying:
    lazy_matrix_mul(list1, list2)
Expecting:
    array([[ 30, -26,  10],
           [ 36, -31,  14],
           [ 42, -36,  18]])
ok
Trying:
    lazy_matrix_mul([[1, 5, 7]], [[3], [5], [8]])
Expecting:
    array([[84]])
ok
Trying:
    lazy_matrix_mul(None, None)
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: Object arrays are not currently supported
**********************************************************************
File "tests/101-lazy_matrix_mul.txt", line 38, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul(None, None)
Expected:
    Traceback (most recent call last):
              ...
    TypeError: Object arrays are not currently supported
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 101-lazy_matrix_mul.txt[7]>", line 1, in <module>
        lazy_matrix_mul(None, None)
      File "/mnt/c/Users/admin/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 25, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
               ^^^^^^^^^^^^^^^^^^^
    ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)
Trying:
    lazy_matrix_mul([[7, 12]], None)
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: Object arrays are not currently supported
**********************************************************************
File "tests/101-lazy_matrix_mul.txt", line 45, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[7, 12]], None)
Expected:
    Traceback (most recent call last):
              ...
    TypeError: Object arrays are not currently supported
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 101-lazy_matrix_mul.txt[8]>", line 1, in <module>
        lazy_matrix_mul([[7, 12]], None)
      File "/mnt/c/Users/admin/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 25, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
               ^^^^^^^^^^^^^^^^^^^
    ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)
Trying:
    lazy_matrix_mul((1, 3, 5), [[1.3], [5.2], [7.7]])
Expecting:
    array([55.4])
ok
Trying:
    lazy_matrix_mul([[3, 3], [4, 4]], "Holberton")
Expecting:
    Traceback (most recent call last):
              ...
    ValueError: Scalar operands are not allowed, use '*' instead
**********************************************************************
File "tests/101-lazy_matrix_mul.txt", line 57, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[3, 3], [4, 4]], "Holberton")
Expected:
    Traceback (most recent call last):
              ...
    ValueError: Scalar operands are not allowed, use '*' instead
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 101-lazy_matrix_mul.txt[10]>", line 1, in <module>
        lazy_matrix_mul([[3, 3], [4, 4]], "Holberton")
      File "/mnt/c/Users/admin/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 25, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
               ^^^^^^^^^^^^^^^^^^^
    numpy.core._exceptions._UFuncNoLoopError: ufunc 'matmul' did not contain a loop with signature matching types (dtype('int64'), dtype('<U9')) -> None
Trying:
    lazy_matrix_mul([(1, 5, 10)], [(1), (5)])
Expecting:
    Traceback (most recent call last):
              ...
    ValueError: shapes (1,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)
**********************************************************************
File "tests/101-lazy_matrix_mul.txt", line 64, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([(1, 5, 10)], [(1), (5)])
Expected:
    Traceback (most recent call last):
              ...
    ValueError: shapes (1,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 101-lazy_matrix_mul.txt[11]>", line 1, in <module>
        lazy_matrix_mul([(1, 5, 10)], [(1), (5)])
      File "/mnt/c/Users/admin/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 25, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
               ^^^^^^^^^^^^^^^^^^^
    ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)
Trying:
    lazy_matrix_mul([[]], ["Holberton"])
Expecting:
    Traceback (most recent call last):
              ...
    ValueError: shapes (1,0) and (1,) not aligned: 0 (dim 1) != 1 (dim 0)
**********************************************************************
File "tests/101-lazy_matrix_mul.txt", line 71, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[]], ["Holberton"])
Expected:
    Traceback (most recent call last):
              ...
    ValueError: shapes (1,0) and (1,) not aligned: 0 (dim 1) != 1 (dim 0)
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 101-lazy_matrix_mul.txt[12]>", line 1, in <module>
        lazy_matrix_mul([[]], ["Holberton"])
      File "/mnt/c/Users/admin/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 25, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
               ^^^^^^^^^^^^^^^^^^^
    numpy.core._exceptions._UFuncNoLoopError: ufunc 'matmul' did not contain a loop with signature matching types (dtype('float64'), dtype('<U9')) -> None
Trying:
    lazy_matrix_mul([], [[1]])
Expecting:
    Traceback (most recent call last):
              ...
    ValueError: shapes (0,) and (1,1) not aligned: 0 (dim 0) != 1 (dim 0)
**********************************************************************
File "tests/101-lazy_matrix_mul.txt", line 78, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([], [[1]])
Expected:
    Traceback (most recent call last):
              ...
    ValueError: shapes (0,) and (1,1) not aligned: 0 (dim 0) != 1 (dim 0)
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 101-lazy_matrix_mul.txt[13]>", line 1, in <module>
        lazy_matrix_mul([], [[1]])
      File "/mnt/c/Users/admin/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 25, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
               ^^^^^^^^^^^^^^^^^^^
    ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 0)
Trying:
    lazy_matrix_mul([[1, 2]], [[]])
Expecting:
    Traceback (most recent call last):
              ...
    ValueError: shapes (1,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)
**********************************************************************
File "tests/101-lazy_matrix_mul.txt", line 85, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[1, 2]], [[]])
Expected:
    Traceback (most recent call last):
              ...
    ValueError: shapes (1,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 101-lazy_matrix_mul.txt[14]>", line 1, in <module>
        lazy_matrix_mul([[1, 2]], [[]])
      File "/mnt/c/Users/admin/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 25, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
               ^^^^^^^^^^^^^^^^^^^
    ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)
Trying:
    lazy_matrix_mul([[1, '1', 1], ['2', 2, '2']], [[3], [3]])
Expecting:
    Traceback (most recent call last):
              ...
    ValueError: shapes (2,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)
**********************************************************************
File "tests/101-lazy_matrix_mul.txt", line 92, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[1, '1', 1], ['2', 2, '2']], [[3], [3]])
Expected:
    Traceback (most recent call last):
              ...
    ValueError: shapes (2,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 101-lazy_matrix_mul.txt[15]>", line 1, in <module>
        lazy_matrix_mul([[1, '1', 1], ['2', 2, '2']], [[3], [3]])
      File "/mnt/c/Users/admin/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 25, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
               ^^^^^^^^^^^^^^^^^^^
    numpy.core._exceptions._UFuncNoLoopError: ufunc 'matmul' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None
Trying:
    lazy_matrix_mul([[2, 4, 6], [3, 6, 9]], [[1], ['2'], [3]])
Expecting:
    Traceback (most recent call last):
              ...
    TypeError: invalid data type for einsum
**********************************************************************
File "tests/101-lazy_matrix_mul.txt", line 99, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[2, 4, 6], [3, 6, 9]], [[1], ['2'], [3]])
Expected:
    Traceback (most recent call last):
              ...
    TypeError: invalid data type for einsum
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 101-lazy_matrix_mul.txt[16]>", line 1, in <module>
        lazy_matrix_mul([[2, 4, 6], [3, 6, 9]], [[1], ['2'], [3]])
      File "/mnt/c/Users/admin/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 25, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
               ^^^^^^^^^^^^^^^^^^^
    numpy.core._exceptions._UFuncNoLoopError: ufunc 'matmul' did not contain a loop with signature matching types (dtype('int64'), dtype('<U21')) -> None
Trying:
    lazy_matrix_mul([[12, 12, 12], [], [14, 14, 14]], [[2], [3], [8]])
Expecting:
    Traceback (most recent call last):
              ...
    ValueError: setting an array element with a sequence.
**********************************************************************
File "tests/101-lazy_matrix_mul.txt", line 106, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[12, 12, 12], [], [14, 14, 14]], [[2], [3], [8]])
Expected:
    Traceback (most recent call last):
              ...
    ValueError: setting an array element with a sequence.
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 101-lazy_matrix_mul.txt[17]>", line 1, in <module>
        lazy_matrix_mul([[12, 12, 12], [], [14, 14, 14]], [[2], [3], [8]])
      File "/mnt/c/Users/admin/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 25, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
               ^^^^^^^^^^^^^^^^^^^
    ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.
Trying:
    lazy_matrix_mul([[2, 2, 2], [4, 4, 4]], [[2], [3, 3]])
Expecting:
    Traceback (most recent call last):
              ...
    ValueError: setting an array element with a sequence.
**********************************************************************
File "tests/101-lazy_matrix_mul.txt", line 113, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[2, 2, 2], [4, 4, 4]], [[2], [3, 3]])
Expected:
    Traceback (most recent call last):
              ...
    ValueError: setting an array element with a sequence.
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 101-lazy_matrix_mul.txt[18]>", line 1, in <module>
        lazy_matrix_mul([[2, 2, 2], [4, 4, 4]], [[2], [3, 3]])
      File "/mnt/c/Users/admin/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 25, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
               ^^^^^^^^^^^^^^^^^^^
    ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
Trying:
    lazy_matrix_mul([[5, 2, 3], [7, 13, 2], [1, 0, 3]], [[2, 3], [6, 9]])
Expecting:
    Traceback (most recent call last):
              ...
    ValueError: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)
**********************************************************************
File "tests/101-lazy_matrix_mul.txt", line 120, in 101-lazy_matrix_mul.txt
Failed example:
    lazy_matrix_mul([[5, 2, 3], [7, 13, 2], [1, 0, 3]], [[2, 3], [6, 9]])
Expected:
    Traceback (most recent call last):
              ...
    ValueError: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)
Got:
    Traceback (most recent call last):
      File "/usr/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest 101-lazy_matrix_mul.txt[19]>", line 1, in <module>
        lazy_matrix_mul([[5, 2, 3], [7, 13, 2], [1, 0, 3]], [[2, 3], [6, 9]])
      File "/mnt/c/Users/admin/alx-higher_level_programming/0x07-python-test_driven_development/101-lazy_matrix_mul.py", line 25, in lazy_matrix_mul
        return np.matmul(m_a, m_b)
               ^^^^^^^^^^^^^^^^^^^
    ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)
Trying:
    lazy_matrix_mul([[1, 2]])
Expecting:
    Traceback (most recent call last):
                    ...
    TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'
ok
Trying:
    lazy_matrix_mul()
Expecting:
    Traceback (most recent call last):
                    ...
    TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'
ok
**********************************************************************
1 items had failures:
  12 of  22 in 101-lazy_matrix_mul.txt
22 tests in 1 items.
10 passed and 12 failed.
***Test Failed*** 12 failures.
